# -*- coding: utf-8 -*-
"""Scraping_scifi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wsFuOKeoTjqtnoMWbcg49jsVyymAcp1D
"""

import pandas as pd

action = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/All Data/action_all.csv")
animation = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/All Data/animation_all.csv")
art_foreign = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/All Data/art_foreign_all.csv")
classics = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/All Data/classics_all.csv")
comedy = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/All Data/comedy_all.csv")
documentary = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/All Data/documentary_all.csv")
drama = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/All Data/drama_all.csv")
horror = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/All Data/horror_all.csv")
kids_family = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/All Data/kids_family_all.csv")
mystery = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/All Data/mystery_all.csv")
romance = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/All Data/romance_all.csv")
scifi = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/All Data/scifi_all.csv")

frames=[action,animation,art_foreign,classics,comedy,documentary,drama,horror,kids_family,mystery,romance,scifi]

all_movie=pd.concat(frames,ignore_index=True,axis=0)

import os
path= r'/Users/jaynanda/Desktop/Assignments/660/Project/All Data/'
all_movie.to_csv(os.path.join(path, r'all_movie.csv'), index=False)