# -*- coding: utf-8 -*-
"""Scraping_scifi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wsFuOKeoTjqtnoMWbcg49jsVyymAcp1D
"""

import pandas as pd

action = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/Unprocessed Data/action.csv")
animation = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/Unprocessed Data/animation.csv")
art_foreign = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/Unprocessed Data/art_foreign.csv")
classics = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/Unprocessed Data/classics.csv")
comedy = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/Unprocessed Data/comedy.csv")
documentary = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/Unprocessed Data/documentary.csv")
drama = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/Unprocessed Data/drama.csv")
horror = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/Unprocessed Data/horror.csv")
kids_family = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/Unprocessed Data/kids_family.csv")
mystery = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/Unprocessed Data/mystery.csv")
romance = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/Unprocessed Data/romance.csv")
scifi = pd.read_csv("/Users/jaynanda/Desktop/Assignments/660/Project/Unprocessed Data/scifi.csv")

frames=[action,animation,art_foreign,classics,comedy,documentary,drama,horror,kids_family,mystery,romance,scifi]

all_movie=pd.concat(frames,ignore_index=True,axis=0)

import os
path= r'/Users/jaynanda/Desktop/Assignments/660/Project/Unprocessed Data/'
all_movie.to_csv(os.path.join(path, r'all_movie.csv'), index=False)